#!/usr/bin/env python3
"""Scans a product repo and writes grounding document drafts to _drafts/.

Called by the /trust map codebase slash command. Each draft is a Markdown
file containing structured observations extracted heuristically from the
product repo. Drafts are meant to be reviewed and edited before being
promoted to finalized grounding documents via /trust approve-drafts.

Usage:
    python codebase_mapper.py <product-repo-path> <grounding-dir> [--force]

Exit codes:
    0  → one or more drafts written (or skipped because already finalized)
    1  → no files could be extracted (repo empty or unreadable)
    2  → invalid arguments or paths
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class DraftResult:
    slot: str
    draft_path: Path
    status: str  # "written" | "skipped_finalized" | "skipped_exists" | "error"
    error: str | None = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "dist", "build",
    ".next", ".nuxt", "coverage", ".pytest_cache", ".mypy_cache",
}

_SOURCE_EXTENSIONS = {
    ".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".java", ".kt",
    ".cs", ".rb", ".rs", ".php", ".swift", ".scala",
}


def _walk(root: Path, max_files: int = 2000) -> list[Path]:
    """Walk repo, skipping ignored dirs, returning source files."""
    results: list[Path] = []
    for path in root.rglob("*"):
        if any(p in _IGNORE_DIRS for p in path.parts):
            continue
        if path.is_file():
            results.append(path)
        if len(results) >= max_files:
            break
    return results


def _relative(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def _read_safe(path: Path, max_bytes: int = 32_768) -> str:
    """Read a text file safely, returning empty string on any error."""
    try:
        content = path.read_bytes()[:max_bytes]
        return content.decode("utf-8", errors="replace")
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Slot: 01-architecture
# ---------------------------------------------------------------------------


def _build_architecture_draft(repo: Path, files: list[Path]) -> str:
    lines: list[str] = [
        "# Architecture — (auto-generated draft)",
        "",
        "> **DRAFT** — Generated by `/trust map codebase`. Review and edit before approving.",
        "> Replace all `TODO` markers with your project's real content.",
        "",
        "---",
        "",
        "## Overview",
        "",
        "TODO: Describe the high-level architecture of this service.",
        "",
    ]

    # README summary
    readme_candidates = ["README.md", "readme.md", "Readme.md"]
    for candidate in readme_candidates:
        readme = repo / candidate
        if readme.exists():
            content = _read_safe(readme, 4096)
            if content:
                lines += [
                    "## Extracted from README",
                    "",
                    "```",
                    content[:2000],
                    "```",
                    "",
            ]
            break

    # Directory tree (top 2 levels)
    lines += ["## Directory structure (top 2 levels)", "", "```"]
    seen_dirs: set[str] = set()
    for f in sorted(files):
        rel = _relative(f, repo)
        parts = rel.replace("\\", "/").split("/")
        if len(parts) >= 1:
            top = parts[0]
            if top not in seen_dirs and top not in _IGNORE_DIRS:
                seen_dirs.add(top)
                lines.append(f"{top}/")
        if len(parts) >= 2:
            two = f"{parts[0]}/{parts[1]}"
            if two not in seen_dirs:
                seen_dirs.add(two)
                lines.append(f"  {parts[1]}/")
    lines += ["```", "", "## Entry points", "", "TODO: List main entry points (e.g. main.go, app.py, src/index.ts).", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Slot: 03-api-contracts
# ---------------------------------------------------------------------------

_ROUTE_PATTERNS = [
    "router.get", "router.post", "router.put", "router.patch", "router.delete",
    "app.get", "app.post", "app.put", "app.patch", "app.delete",
    "@Get(", "@Post(", "@Put(", "@Patch(", "@Delete(",
    "@app.route", "@router.route",
    'path("/)', "path('/')", 'method="GET"', 'method="POST"',
]


def _build_contracts_draft(repo: Path, files: list[Path]) -> str:
    lines: list[str] = [
        "# API Contracts — (auto-generated draft)",
        "",
        "> **DRAFT** — Generated by `/trust map codebase`. Review and edit before approving.",
        "",
        "---",
        "",
        "## Detected routes / endpoints",
        "",
    ]

    found_any = False
    for f in files:
        if f.suffix not in _SOURCE_EXTENSIONS:
            continue
        content = _read_safe(f, 16_384)
        matching_lines = [
            (i + 1, ln.rstrip())
            for i, ln in enumerate(content.splitlines())
            if any(pat in ln for pat in _ROUTE_PATTERNS)
        ]
        if matching_lines:
            found_any = True
            rel = _relative(f, repo)
            lines.append(f"### `{rel}`")
            lines.append("")
            lines.append("```")
            for lineno, ln in matching_lines[:20]:
                lines.append(f"{lineno:4d} | {ln}")
            if len(matching_lines) > 20:
                lines.append(f"     | ... ({len(matching_lines) - 20} more)")
            lines.append("```")
            lines.append("")

    if not found_any:
        lines.append("No route definitions auto-detected. Fill in manually.")
        lines.append("")

    lines += [
        "## Breaking change rules",
        "",
        "TODO: Document which fields/endpoints are considered stable contracts.",
        "TODO: Define the deprecation policy.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Slot: 04-data-model
# ---------------------------------------------------------------------------

_MIGRATION_GLOBS = ["**/migrations/*.sql", "**/migrations/*.py", "**/db/migrate/*.rb"]
_SCHEMA_FILES = ["prisma/schema.prisma", "schema.prisma", "db/schema.rb", "database/schema.sql"]


def _build_data_draft(repo: Path, files: list[Path]) -> str:
    lines: list[str] = [
        "# Data Model — (auto-generated draft)",
        "",
        "> **DRAFT** — Generated by `/trust map codebase`. Review and edit before approving.",
        "",
        "---",
        "",
    ]

    # Schema files
    for schema_rel in _SCHEMA_FILES:
        schema = repo / schema_rel
        if schema.exists():
            content = _read_safe(schema, 8_192)
            lines += [
                f"## Schema: `{schema_rel}`",
                "",
                "```",
                content[:4000],
                "```" if len(content) <= 4000 else f"```\n... (truncated at 4000 bytes of {len(content)})",
                "",
            ]

    # Migration files
    migration_files = [
        f for f in files
        if "migration" in _relative(f, repo).lower()
        and f.suffix in (".sql", ".py", ".rb", ".ts", ".js")
    ]
    if migration_files:
        lines += ["## Migration files detected", ""]
        for mf in sorted(migration_files)[:20]:
            lines.append(f"- `{_relative(mf, repo)}`")
        lines.append("")

    lines += [
        "## Key constraints",
        "",
        "TODO: Document NOT NULL constraints, unique indexes, foreign keys.",
        "TODO: Document fields that are part of public APIs (can't be removed).",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Slot: 05-conventions
# ---------------------------------------------------------------------------

_CONVENTION_FILES = [
    ".eslintrc", ".eslintrc.json", ".eslintrc.js", ".eslintrc.yaml",
    ".prettierrc", ".prettierrc.json", ".prettierrc.yaml",
    "pyproject.toml", ".flake8", "setup.cfg",
    ".golangci.yml", ".golangci.yaml",
    "rubocop.yml", ".rubocop.yml",
]


def _build_conventions_draft(repo: Path, files: list[Path]) -> str:
    lines: list[str] = [
        "# Conventions — (auto-generated draft)",
        "",
        "> **DRAFT** — Generated by `/trust map codebase`. Review and edit before approving.",
        "",
        "---",
        "",
        "## Linter / formatter configuration",
        "",
    ]

    found_any = False
    for cfg_name in _CONVENTION_FILES:
        cfg = repo / cfg_name
        if cfg.exists():
            found_any = True
            content = _read_safe(cfg, 4_096)
            lines += [
                f"### `{cfg_name}`",
                "",
                "```",
                content[:2000],
                "```",
                "",
            ]

    if not found_any:
        lines += ["No linter/formatter config detected.", ""]

    lines += [
        "## Naming conventions",
        "",
        "TODO: Document naming conventions (files, functions, variables, classes).",
        "",
        "## Logging conventions",
        "",
        "TODO: Document approved logger patterns. Forbid console.log/print in production code?",
        "",
        "## Error handling conventions",
        "",
        "TODO: Document how errors must be handled and propagated.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Slot: 06-security-policy
# ---------------------------------------------------------------------------

_AUTH_PATTERNS = [
    "authenticate", "authorize", "authMiddleware", "jwtVerify",
    "verifyToken", "requireAuth", "@auth", "session.user",
    "Bearer", "JWT", "passport", "oauth",
]

_SECRET_PATTERNS = [
    "process.env.", "os.environ", "getenv(", "secrets.get(",
    "Vault", "AWS_SECRET", "AZURE_CLIENT_SECRET",
]

_CORS_PATTERNS = [
    "cors(", "CorsMiddleware", "Access-Control-Allow-Origin",
    "origins=", "allowed_origins",
]


def _build_security_draft(repo: Path, files: list[Path]) -> str:
    lines: list[str] = [
        "# Security Policy — (auto-generated draft)",
        "",
        "> **DRAFT** — Generated by `/trust map codebase`. Review and edit before approving.",
        "> This file requires human review — the mapper only detects patterns, not intent.",
        "",
        "---",
        "",
    ]

    def _section(title: str, patterns: list[str], label: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        matches: list[tuple[str, int, str]] = []
        for f in files:
            if f.suffix not in _SOURCE_EXTENSIONS:
                continue
            content = _read_safe(f, 16_384)
            for i, ln in enumerate(content.splitlines()):
                if any(p in ln for p in patterns):
                    matches.append((_relative(f, repo), i + 1, ln.strip()))
        if matches:
            lines.append(f"Detected {label} patterns:")
            lines.append("")
            lines.append("```")
            for rel, lineno, ln in matches[:15]:
                lines.append(f"{rel}:{lineno} | {ln[:120]}")
            if len(matches) > 15:
                lines.append(f"... ({len(matches) - 15} more)")
            lines.append("```")
        else:
            lines.append(f"No {label} patterns detected.")
        lines.append("")
        lines.append("TODO: Document the rules for this area.")
        lines.append("")

    _section("secrets-management", _SECRET_PATTERNS, "secrets/env-var")
    _section("authentication", _AUTH_PATTERNS, "authentication")
    _section("network-security", _CORS_PATTERNS, "CORS")

    lines += [
        "## input-validation",
        "",
        "TODO: Document parameterized query requirements, allowlist validation rules.",
        "",
        "## authorization",
        "",
        "TODO: Document the authorization model (RBAC, ownership checks, etc.).",
        "",
        "## cryptography",
        "",
        "TODO: List approved and forbidden algorithms for this project.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Mapper entry point
# ---------------------------------------------------------------------------


@dataclass
class MapperConfig:
    repo: Path
    grounding_dir: Path
    force: bool = False


_SLOTS: list[tuple[str, str]] = [
    ("01-architecture.md", "architecture"),
    ("03-api-contracts.md", "contracts"),
    ("04-data-model.md", "data"),
    ("05-conventions.md", "conventions"),
    ("06-security-policy.md", "security"),
]

_BUILDERS = {
    "architecture": _build_architecture_draft,
    "contracts": _build_contracts_draft,
    "data": _build_data_draft,
    "conventions": _build_conventions_draft,
    "security": _build_security_draft,
}


def run_mapper(cfg: MapperConfig) -> list[DraftResult]:
    """Scan the product repo and write draft grounding docs."""
    drafts_dir = cfg.grounding_dir / "_drafts"
    drafts_dir.mkdir(parents=True, exist_ok=True)

    files = _walk(cfg.repo)
    results: list[DraftResult] = []

    for filename, slot_key in _SLOTS:
        draft_path = drafts_dir / filename
        finalized_path = cfg.grounding_dir / filename

        # Skip if already finalized (unless --force)
        if finalized_path.exists() and not cfg.force:
            results.append(DraftResult(
                slot=filename,
                draft_path=draft_path,
                status="skipped_finalized",
            ))
            continue

        # Skip existing drafts (unless --force)
        if draft_path.exists() and not cfg.force:
            results.append(DraftResult(
                slot=filename,
                draft_path=draft_path,
                status="skipped_exists",
            ))
            continue

        try:
            builder = _BUILDERS[slot_key]
            content = builder(cfg.repo, files)
            draft_path.write_text(content, encoding="utf-8")
            results.append(DraftResult(
                slot=filename,
                draft_path=draft_path,
                status="written",
            ))
        except Exception as exc:
            results.append(DraftResult(
                slot=filename,
                draft_path=draft_path,
                status="error",
                error=str(exc),
            ))

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    args = sys.argv[1:]
    force = "--force" in args
    args = [a for a in args if a != "--force"]

    if len(args) != 2:
        print(
            "Usage: codebase_mapper.py <product-repo-path> <grounding-dir> [--force]",
            file=sys.stderr,
        )
        return 2

    repo = Path(args[0])
    grounding_dir = Path(args[1])

    if not repo.is_dir():
        print(f"Error: product repo not found or not a directory: {repo}", file=sys.stderr)
        return 2

    if not grounding_dir.is_dir():
        print(f"Error: grounding-dir not found or not a directory: {grounding_dir}", file=sys.stderr)
        return 2

    cfg = MapperConfig(repo=repo, grounding_dir=grounding_dir, force=force)
    results = run_mapper(cfg)

    written = [r for r in results if r.status == "written"]
    skipped_fin = [r for r in results if r.status == "skipped_finalized"]
    skipped_ex = [r for r in results if r.status == "skipped_exists"]
    errors = [r for r in results if r.status == "error"]

    for r in results:
        if r.status == "written":
            print(f"  ✅ _drafts/{r.slot}  (written)")
        elif r.status == "skipped_finalized":
            print(f"  ⏭️  {r.slot}  (skipped — already finalized)")
        elif r.status == "skipped_exists":
            print(f"  ⏭️  _drafts/{r.slot}  (skipped — draft exists, use --force to overwrite)")
        elif r.status == "error":
            print(f"  ❌ _drafts/{r.slot}  (error: {r.error})", file=sys.stderr)

    print(
        f"\n{len(written)} draft(s) written, "
        f"{len(skipped_fin) + len(skipped_ex)} skipped, "
        f"{len(errors)} error(s)"
    )

    if written:
        print("Next: review drafts, then run /trust approve-drafts")

    return 0 if not errors or written else 1


if __name__ == "__main__":
    sys.exit(main())
