"""Migration script: pilot setup → enterprise layout.

Converts an existing pilot setup repo into an enterprise three-layer layout:

    Before (pilot):
        payments-team-trust/
          trust.config.yaml
          grounding/
          checklists/
          targets/
          runs/

    After (enterprise):
        payments-team-enterprise/
          trust.config.yaml          ← new enterprise config
          corp/
            grounding/               ← empty (platform team fills this)
            checklists/              ← empty
            overrides.yaml           ← empty
          team/
            grounding/               ← copied from pilot grounding/
            checklists/              ← copied from pilot checklists/
            specs/                   ← empty
            overrides.yaml           ← empty
          personal/
            .gitkeep                 ← per-dev local; never committed

Usage:

    python scripts/migrate_pilot_to_enterprise.py \\
        --source ~/work/payments-team-trust \\
        --output ~/work/payments-team-enterprise \\
        [--dry-run]

The script NEVER modifies the source directory. The output directory must
not already exist (to prevent accidental overwrites).
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Migration logic
# ---------------------------------------------------------------------------


def _copy_dir(src: Path, dst: Path) -> list[str]:
    """Copy src → dst recursively. Returns list of copied paths."""
    if not src.exists():
        return []
    dst.mkdir(parents=True, exist_ok=True)
    copied = []
    for item in src.rglob("*"):
        if item.is_file():
            rel = item.relative_to(src)
            dest_file = dst / rel
            dest_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, dest_file)
            copied.append(str(rel))
    return copied


def _write_empty_file(path: Path, name: str) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / name).write_text("", encoding="utf-8")


def _build_enterprise_config(source: Path, output: Path) -> str:
    """Generate an enterprise trust.config.yaml based on the pilot config."""
    try:
        pilot_text = (source / "trust.config.yaml").read_text(encoding="utf-8")
    except OSError:
        pilot_text = ""

    # Extract the agents block from pilot config (simple line extraction)
    agents_lines: list[str] = []
    in_agents = False
    for line in pilot_text.splitlines():
        if line.startswith("agents:"):
            in_agents = True
            agents_lines.append(line)
            continue
        if in_agents:
            if line and not line[0].isspace() and not line.startswith("  "):
                in_agents = False
            else:
                agents_lines.append(line)

    agents_block = "\n".join(agents_lines) if agents_lines else (
        "agents:\n"
        "  - id: security\n"
        "    skill: trust-security-review\n"
        "    checklist: team/checklists/security.checklist.md\n"
        "    enabled: true\n"
    )

    return f"""# TRUST — Enterprise Profile Configuration
# Migrated from pilot setup at: {source}
# Generated by: scripts/migrate_pilot_to_enterprise.py
#
# NEXT STEPS:
#   1. Review and fill corp/grounding/ with company-wide policies
#   2. Review and fill corp/checklists/ with company-wide rules
#   3. Set TRUST_SETUP_PATH={output}
#   4. Run /trust doctor to validate the new setup

framework: trust
version: "1.2"
profile_type: enterprise

layers:
  corp:
    path: ./corp
    priority: 1
    override_policy: require_reason
  team:
    path: ./team
    priority: 2
    override_policy: require_reason
  personal:
    path: ${{HOME}}/.trust/personal
    priority: 3
    override_policy: allow

grounding:
  required:
    - source: "layer-corp"
      path: "06-security-policy.md"
      purpose: "Company-wide security baseline"
    - source: "layer-team"
      path: "01-architecture.md"
      purpose: "Squad architecture overview"

{agents_block}

confidence_threshold: 0.85
runs_base_dir: "./runs"
retention_policy: all_versioned

# Uncomment to enable traceability:
# traceability:
#   enabled: true
#   jira:
#     base_url: "https://empresa.atlassian.net"
#     auth:
#       user_env: "JIRA_USER"
#       token_env: "JIRA_TOKEN"
"""


_OVERRIDES_TEMPLATE = """\
# Layer overrides — rules this layer overrides from lower-priority layers.
# Each override requires a reason when override_policy is require_reason.
#
# Example:
#   overrides:
#     - rule_id: SEC-003
#       action: disable
#       reason: "We use HSM — hardware controls replace this software check"
#
#     - rule_id: PERF-001
#       action: raise_threshold
#       new_threshold: 0.90
#       reason: "Strict latency SLAs in this domain require higher confidence"

overrides: []
"""


def migrate(source: Path, output: Path, dry_run: bool = False) -> int:
    """Run the migration. Returns exit code (0 = success)."""
    print(f"\n🔄 TRUST pilot → enterprise migration")
    print(f"   source:  {source}")
    print(f"   output:  {output}")
    print(f"   dry-run: {dry_run}\n")

    # Validate source
    if not source.is_dir():
        print(f"❌ Source directory not found: {source}")
        return 1
    if not (source / "trust.config.yaml").exists():
        print(f"❌ No trust.config.yaml in source. Is this a TRUST setup repo?")
        return 1

    # Validate output
    if output.exists():
        print(f"❌ Output directory already exists: {output}")
        print(f"   Remove it first or choose a different path.")
        return 1

    steps: list[tuple[str, str]] = []

    # 1. Create directory structure
    dirs = [
        output / "corp" / "grounding",
        output / "corp" / "checklists",
        output / "team" / "grounding",
        output / "team" / "checklists",
        output / "team" / "specs",
        output / "personal",
        output / "runs",
    ]
    for d in dirs:
        steps.append(("mkdir", str(d)))

    # 2. Copy pilot grounding → team/grounding
    pilot_grounding = source / "grounding"
    if pilot_grounding.is_dir():
        for f in pilot_grounding.rglob("*"):
            if f.is_file():
                rel = f.relative_to(pilot_grounding)
                steps.append(("copy", f"{f} → {output / 'team' / 'grounding' / rel}"))

    # 3. Copy pilot checklists → team/checklists
    pilot_checklists = source / "checklists"
    if pilot_checklists.is_dir():
        for f in pilot_checklists.rglob("*"):
            if f.is_file():
                rel = f.relative_to(pilot_checklists)
                steps.append(("copy", f"{f} → {output / 'team' / 'checklists' / rel}"))

    # 4. Write stub files
    steps.append(("write", str(output / "trust.config.yaml")))
    steps.append(("write", str(output / "corp" / "overrides.yaml")))
    steps.append(("write", str(output / "team" / "overrides.yaml")))
    steps.append(("write", str(output / "personal" / ".gitkeep")))

    # Print plan
    print(f"{'DRY RUN: ' if dry_run else ''}Steps:")
    for action, target in steps:
        icon = {"mkdir": "📁", "copy": "📋", "write": "✍️"}.get(action, "•")
        print(f"  {icon} {action}: {target}")

    if dry_run:
        print(f"\n✅ Dry run complete. {len(steps)} steps would run.")
        return 0

    print()

    # Execute
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    copied_grounding = _copy_dir(pilot_grounding, output / "team" / "grounding")
    copied_checklists = _copy_dir(pilot_checklists, output / "team" / "checklists")

    enterprise_config = _build_enterprise_config(source, output)
    (output / "trust.config.yaml").write_text(enterprise_config, encoding="utf-8")
    (output / "corp" / "overrides.yaml").write_text(_OVERRIDES_TEMPLATE, encoding="utf-8")
    (output / "team" / "overrides.yaml").write_text(_OVERRIDES_TEMPLATE, encoding="utf-8")
    (output / "personal" / ".gitkeep").write_text("", encoding="utf-8")

    print(f"✅ Migration complete!")
    print(f"   Copied grounding:  {len(copied_grounding)} files → team/grounding/")
    print(f"   Copied checklists: {len(copied_checklists)} files → team/checklists/")
    print(f"\n📋 Next steps:")
    print(f"   1. Review {output}/trust.config.yaml")
    print(f"   2. Add company-wide policies to {output}/corp/grounding/")
    print(f"   3. export TRUST_SETUP_PATH={output}")
    print(f"   4. /trust doctor\n")

    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Migrate a TRUST pilot setup to the enterprise profile."
    )
    parser.add_argument(
        "--source",
        required=True,
        type=Path,
        help="Path to the existing pilot setup repo.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path where the new enterprise setup will be created.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without making any changes.",
    )

    args = parser.parse_args()
    sys.exit(migrate(args.source.resolve(), args.output.resolve(), args.dry_run))


if __name__ == "__main__":
    main()
